Repository nix-community/nixd, pull requests merged in 2023-06, with the labels that each got.

#119 lspserver: remove the named mutex when logger startup
  lib/lspserver/include/lspserver/Logger.h
  lib/lspserver/src/Logger.cpp
Labels: bug

#115 nixd/completion/options: send example field to our user
  lib/nixd/include/nixd/nix/Option.h
  lib/nixd/src/ServerWorker.cpp
  lib/nixd/src/nix/Option.cpp
Labels: enhancement

#113 nixd: goto definition for derivations
  lib/nixd/include/nixd/nix/Value.h
  lib/nixd/src/ServerWorker.cpp
  lib/nixd/src/nix/Value.cpp
  tools/nixd/test/goto-definition-derivation.md
Labels: enhancement

#117 nixd/definition: goto definition for any evaluated non-pos-discarded values
  lib/nixd/src/ServerWorker.cpp
Labels: enhancement

#127 vendor: use git revision if possible
  default.nix
  meson.build
  tools/nixd/nixd.cpp
Labels: vendor

#132 editors/nvim-lsp: fix don't display diagnostic information
  editors/nvim-lsp.nix
Labels: editors

#130 nixd/AST: lookup values if it is statically binds to some value
  lib/nixd/include/nixd/AST.h
  lib/nixd/src/AST.cpp
  tools/nixd/test/lambda-value-lookup.md
Labels: enhancement

#146 nixd: fix concurrency-related bugs
  lib/nixd/include/nixd/Server.h
  lib/nixd/src/ServerController.cpp
  lib/nixd/src/ServerOption.cpp
Labels: bug

#148 nixd/documentSymbol: init
  lib/lspserver/include/lspserver/Protocol.h
  lib/nixd/include/nixd/JSONSerialization.h
  lib/nixd/include/nixd/Server.h
  lib/nixd/src/JSONSerialization.cpp
  lib/nixd/src/ServerController.cpp
  lib/nixd/src/ServerEval.cpp
  tools/nixd/test/document-symbol.md
  tools/nixd/test/initialize.md
Labels: enhancement

#152 nixd/diagnostics: imporve diagnostic position & tracing
  lib/nixd/include/nixd/Diagnostic.h
  lib/nixd/include/nixd/Position.h
  lib/nixd/include/nixd/Server.h
  lib/nixd/include/nixd/nix/PosAdapter.h
  lib/nixd/src/Diagnostic.cpp
  lib/nixd/src/ServerEval.cpp
  lib/nixd/test/diagnostic.cpp
  tools/nixd/test/diagnostic-trace.md
Labels: enhancement

#153 nixd/rename: support `textDocument/rename`
  lib/nixd/include/nixd/AST.h
  lib/nixd/include/nixd/JSONSerialization.h
  lib/nixd/include/nixd/Server.h
  lib/nixd/src/AST.cpp
  lib/nixd/src/JSONSerialization.cpp
  lib/nixd/src/ServerController.cpp
  lib/nixd/src/ServerEval.cpp
  tools/nixd/test/initialize.md
  tools/nixd/test/rename-definition.md
  tools/nixd/test/rename-prepare-no.md
  tools/nixd/test/rename-prepare-ok.md
  tools/nixd/test/rename-variable.md
Labels: enhancement

#162 docs/examples: examples about how to use nixd
  README.md
  docs/examples/flake/.nixd.json
  docs/examples/flake/default.nix
  docs/examples/flake/flake.lock
  docs/examples/flake/flake.nix
  docs/examples/options/home-manager/.nixd.json
  docs/examples/options/home-manager/flake.lock
  docs/examples/options/home-manager/flake.nix
  docs/examples/options/nixos/.nixd.json
  docs/examples/options/nixos/module.nix
  docs/examples/package/.nixd.json
  docs/examples/package/package.nix
  docs/user-guide.md
Labels: documentation

#163 docs/user-guide: update the user-guide for flakes
  docs/user-guide.md
Labels: documentation

#172 vendor: fix nixd on darwin
  .github/workflows/build.yml
  .github/workflows/nix.yml
  default.nix
  flake.nix
  lib/lspserver/src/Logger.cpp
  lib/nixd/src/ServerController.cpp
Labels: vendor

#175 nixd/option: fix crash on invalid option set
  lib/nixd/src/ServerOption.cpp
  tools/nixd/test/option-invalid-crash.md
  tools/nixd/test/option-invalid-goto-declaration.md
Labels: bug

#177 nixd/driver: don't write stack dump file
  tools/nixd/nixd.cpp
Labels: bug
