Repository nix-community/nixd, pull requests merged in 2023-07, with the labels that each got.

#189 nixd/documentLinkProvider: conform closer to spec
  nixd/lib/Server/Controller.cpp
  nixd/tools/nixd/test/initialize.md
Labels: bug

#201 lspserver: unlock the PendingCallsLock before calling callback
  lspserver/src/LSPServer.cpp
Labels: bug

#202 nixd/Parser: add thread_local to lexer.l
  nixd/include/nixd/Lexer/Prologue.h
Labels: upstream

#211 nixd/Server: fix outdated draft version for static analysis
  nixd/include/nixd/Server/ASTManager.h
  nixd/include/nixd/Server/Server.h
  nixd/lib/Server/ASTManager.cpp
  nixd/lib/Server/Controller.cpp
Labels: bug

#221 docs/editor-setup: add coc.nvim
  docs/editor-setup.md
Labels: documentation

#220 docs/examples: talking about cwd
  docs/examples/README.md
Labels: documentation

#219 docs/readme: add project structure
  README.md
Labels: documentation
