Repository nix-community/nixd, pull requests merged in 2024-01, with the labels that each got.

#304 nixd: add a json schema
  nixd/docs/nixd-schema.json
  nixd/docs/user-guide.md
Labels: documentation

#306 libnixf: fix lexer float trailing `e` args
  libnixf/src/Parse/Lexer.cpp
  libnixf/test/Parse/Lexer.cpp
Labels: bug

#305 libnixf: fix Lexer location indexes
  libnixf/src/Parse/Lexer.h
  libnixf/test/Parse/Parser.cpp
Labels: bug

#303 nixd-next: text document synchronization
  nixd-next/tools/nixd/src/Controller.cpp
  nixd-next/tools/nixd/test/initialize.md
Labels: enhancement

#319 libnixf: fix node range of `Binding` & `ExprAttrs`
  libnixf/src/Parse/Parser.cpp
  libnixf/test/Parse/Parser.cpp
Labels: bug

#318 nixd: support hover
  nixd/tools/nixd/src/Controller.cpp
  nixd/tools/nixd/test/hover.md
  nixd/tools/nixd/test/initialize.md
Labels: enhancement

#323 libnixf: add semantic analysis for `AttrSet`s
  libnixf/include/nixf/Basic/DiagnosticKinds.inc
  libnixf/include/nixf/Basic/Nodes.h
  libnixf/include/nixf/Basic/UniqueOrRaw.h
  libnixf/include/nixf/Sema/Lowering.h
  libnixf/meson.build
  libnixf/src/Basic/Nodes.cpp
  libnixf/src/Sema/Lowering.cpp
  libnixf/src/Sema/Lowering.h
  libnixf/test/Basic/Nodes.cpp
  libnixf/test/Sema/Lowering.cpp
  nixd/tools/nixd/src/Controller.cpp
Labels: libnixf:sema

#330 libnixf: parse expr_app
  libnixf/include/nixf/Basic/NodeKinds.inc
  libnixf/include/nixf/Basic/Nodes.h
  libnixf/src/Parse/Parser.cpp
  libnixf/src/Parse/Parser.h
  libnixf/test/Parse/Parser.cpp
Labels: libnixf:parse

#331 libnixf: parse list_expr
  libnixf/include/nixf/Basic/NodeKinds.inc
  libnixf/include/nixf/Basic/Nodes.h
  libnixf/src/Parse/Parser.cpp
  libnixf/src/Parse/Parser.h
  libnixf/src/Parse/Token.h
  libnixf/test/Parse/Parser.cpp
Labels: libnixf:parse

#332 libnixf/Parse: fix range for AttrName (String/Expr)
  libnixf/include/nixf/Basic/Nodes.h
  libnixf/src/Parse/Parser.cpp
  libnixf/test/Parse/Parser.cpp
  libnixf/test/Sema/Lowering.cpp
Labels: libnixf:parse

#333 libnixf/Sema: lowering inherit
  libnixf/include/nixf/Basic/DiagnosticKinds.inc
  libnixf/include/nixf/Basic/Range.h
  libnixf/src/Sema/Lowering.cpp
  libnixf/src/Sema/Lowering.h
  libnixf/test/Sema/Lowering.cpp
Labels: libnixf:sema
