Repository nix-community/nixd, pull requests merged in 2025-02, with the labels that each got.

#646 docs: fix typo `opitons` → `options`
  nixd/docs/configuration.md
Labels: documentation

#648 libnixf: generate token spelling from python script
  libnixf/include/nixf/Basic/Nodes/Op.h
  libnixf/include/nixf/Basic/TokenKinds.h
  libnixf/include/nixf/Basic/TokenKinds.inc
  libnixf/include/nixf/Basic/Tokens.inc
  libnixf/src/Parse/Lexer.cpp
  libnixf/src/Parse/ParseOp.cpp
  libnixf/src/Parse/ParseSupport.cpp
  libnixf/src/Parse/Token.h
  libnixf/src/Parse/TokenKinds.inc.py
  libnixf/src/Parse/Tokens.h.py
  libnixf/src/Parse/tokens.py
  libnixf/src/meson.build
  libnixf/test/Parse/ParseOp.cpp
Labels: bug

#650 libnixf: diagose "or" keyword used as a binary operator
  libnixf/src/Basic/diagnostic.py
  libnixf/src/Parse/ParseOp.cpp
  libnixf/test/Parse/ParseOp.cpp
Labels: enhancement, libnixf:parse
